services:
  nginx:
    image: nginx:1.27-alpine
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend

  frontend:
    image: 952732862406.dkr.ecr.us-east-1.amazonaws.com/vinu-frontend:latest
    restart: always
    expose:
      - "80"
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    image: 952732862406.dkr.ecr.us-east-1.amazonaws.com/vinu-backend:latest
    restart: always
    environment:
      DB_HOST: db
      DB_USER: appuser
      DB_PASS: apppass
      DB_NAME: appdb
    expose:
      - "4000"
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/api/hello"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: mysql:8.4
    restart: always
    environment:
      MYSQL_DATABASE: appdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uappuser", "-papppass"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  dbdata:
